spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mydb
        username: root
        password: 3382149m
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-name: google
                        client-id: 231990703203-kgphbr682kjsvj21t6duoihjo9jl8opb.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8080/login/oauth2/code/google
                        authorization-grant-type: authorization_code
                        scope: profile, email
                    kakao:
                        client-name: kakao
                        client-id: 2f89eaa2414b087287bacffe0795a87a
                        client-secret: yzlKmySSQ8K9z0ZmgNbNb077IELtNzA0
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: POST
                        scope: profile_nickname, account_email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

    jwt:
        secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb


